
nginx:
  restart: always 
  build: ./nginx
  links:
    - socket-1
  ports:
   - "3000:80"

socket-1:
  restart: always 
  build: ./server
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=socket-1

redis:
  restart: always 
  image: redis:alpine
  expose:
    - "6379"
